name: Dev Stage Production

on:
  workflow_dispatch:

jobs:

  development:
    name: Deploy to Development
    runs-on: ubuntu-latest

    environment:
      name: development

    steps:
      - name: Development deployment
        run: |
          echo "Deploying application to DEVELOPMENT"
          echo "Development deployment completed"


  staging:
    name: Deploy to Staging
    needs: development
    runs-on: ubuntu-latest

    environment:
      name: staging

    steps:
      - name: Staging deployment
        run: |
          echo "Deploying application to STAGING"
          echo "Staging deployment completed"


  production:
    name: Deploy to Production
    needs: staging
    runs-on: ubuntu-latest

    environment:
      name: production

    steps:
      - name: Production deployment
        run: |
          echo "Deploying application to PRODUCTION"
          echo "Production deployment completed"
